# Test configuration for orchestration
# This file is used by celery_app.py and dispatch.py

# System overview (used by dispatch.py for display)
system:
  description: "Minimal distributed test system"
  workers: 2

# Test scenario (used by dispatch.py for display)
test_scenario:
  description: "Basic two-task execution test"

# RabbitMQ configuration (used by celery_app.py for broker URL)
rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest

# Task routing configuration (used by celery_app.py for queue routing)
task_routing:
  task_a: queue_a  # Processed by worker-a
  task_b: queue_b  # Processed by worker-b

# Celery retry configuration (used by celery_app.py for retry settings)
retry_config:
  max_retries: 3
  retry_delay: 60
  retry_backoff: true
  retry_backoff_max: 600
  retry_jitter: true
